// app/lib/uiLabels.ts
import { Locale } from './i18n'

/**
 * UI labels and component text translations
 * For all hardcoded text in page components
 */

export const UI_LABELS: Record<Locale, {
    // Page titles
    vision: string
    mission: string
    about: string
    research: string
    technology: string
    platform: string
    contact: string
    faq: string

    // Common labels
    connect: string
    email: string
    follow: string
    location: string
    name: string
    message: string
    organization: string
    submit: string
    ourMission: string
    ourVision: string
    useCase: string
    useCases: string
    theChallenge: string
    ourSolution: string

    // Research page
    philosophy: string
    whitepaper: string
    downloadPDF: string
    researchPublications: string
    authors: string
    published: string
    openInNewTab: string
    moreResearchComingSoon: string

    // About & FAQ page
    founder: string
    ourApproach: string
    support: string
    frequentlyAskedQuestions: string
    stillHaveQuestions: string
    contactUs: string
    findAnswers: string

    // Header
    headerTagline: string
    brandName: string
}> = {
    'en': {
        vision: 'Vision',
        mission: 'Mission',
        about: 'About',
        research: 'Research',
        technology: 'Technology',
        platform: 'Platform',
        contact: 'Contact',
        faq: 'FAQ',
        connect: 'Connect',
        email: 'Email',
        follow: 'Follow',
        location: 'Location',
        name: 'Name',
        message: 'Message',
        organization: 'Organization',
        submit: 'Submit',
        ourMission: 'Our Mission',
        ourVision: 'Our Vision',
        useCase: 'Use Case',
        useCases: 'Use Cases',
        theChallenge: 'The Challenge',
        ourSolution: 'Our Solution',
        philosophy: 'Philosophy',
        whitepaper: 'Whitepaper',
        downloadPDF: 'Download PDF',
        researchPublications: 'Research Publications',
        authors: 'Authors',
        published: 'Published',
        openInNewTab: 'Open in New Tab',
        moreResearchComingSoon: 'More research publications coming soon. Follow us on social media for updates.',
        founder: 'Founder',
        ourApproach: 'Our Approach',
        support: 'Support',
        frequentlyAskedQuestions: 'Frequently Asked Questions',
        stillHaveQuestions: 'Still have questions?',
        contactUs: 'Contact Us',
        findAnswers: 'Find answers to common questions about YugNex Technology, our platform, and how we\'re building the future of software engineering.',
        headerTagline: 'Foundational AI Systems Lab · From India to the World',
        brandName: 'YugNex',
    },
    'en-IN': {
        vision: 'Vision',
        mission: 'Mission',
        about: 'About',
        research: 'Research',
        technology: 'Technology',
        platform: 'Platform',
        contact: 'Contact',
        faq: 'FAQ',
        connect: 'Connect',
        email: 'Email',
        follow: 'Follow',
        location: 'Location',
        name: 'Name',
        message: 'Message',
        organization: 'Organisation',
        submit: 'Submit',
        ourMission: 'Our Mission',
        ourVision: 'Our Vision',
        useCase: 'Use Case',
        useCases: 'Use Cases',
        theChallenge: 'The Challenge',
        ourSolution: 'Our Solution',
        philosophy: 'Philosophy',
        whitepaper: 'Whitepaper',
        downloadPDF: 'Download PDF',
        researchPublications: 'Research Publications',
        authors: 'Authors',
        published: 'Published',
        openInNewTab: 'Open in New Tab',
        moreResearchComingSoon: 'More research publications coming soon. Follow us on social media for updates.',
        founder: 'Founder',
        ourApproach: 'Our Approach',
        support: 'Support',
        frequentlyAskedQuestions: 'Frequently Asked Questions',
        stillHaveQuestions: 'Still have questions?',
        contactUs: 'Contact Us',
        findAnswers: 'Find answers to common questions about YugNex Technology, our platform, and how we\'re building the future of software engineering.',
        headerTagline: 'Foundational AI Systems Lab · From India to the World',
        brandName: 'YugNex',
    },
    'hi': {
        vision: 'विज़न',
        mission: 'मिशन',
        about: 'हमारे बारे में',
        research: 'अनुसंधान',
        technology: 'प्रौद्योगिकी',
        platform: 'प्लेटफॉर्म',
        contact: 'संपर्क करें',
        faq: 'सामान्य प्रश्न',
        connect: 'जुड़ें',
        email: 'ईमेल',
        follow: 'फॉलो करें',
        location: 'स्थान',
        name: 'नाम',
        message: 'संदेश',
        organization: 'संगठन',
        submit: 'भेजें',
        ourMission: 'हमारा मिशन',
        ourVision: 'हमारी दृष्टि',
        useCase: 'उपयोग मामला',
        useCases: 'उपयोग के मामले',
        theChallenge: 'चुनौती',
        ourSolution: 'हमारा समाधान',
        philosophy: 'दर्शन',
        whitepaper: 'श्वेतपत्र',
        downloadPDF: 'PDF डाउनलोड करें',
        researchPublications: 'शोध प्रकाशन',
        authors: 'लेखक',
        published: 'प्रकाशित',
        openInNewTab: 'नए टैब में खोलें',
        moreResearchComingSoon: 'जल्द ही अधिक शोध प्रकाशन आ रहे हैं। अपडेट के लिए हमें सोशल मीडिया पर फॉलो करें।',
        founder: 'संस्थापक',
        ourApproach: 'हमारा दृष्टिकोण',
        support: 'समर्थन',
        frequentlyAskedQuestions: 'अक्सर पूछे जाने वाले प्रश्न',
        stillHaveQuestions: 'अभी भी प्रश्न हैं?',
        contactUs: 'हमसे संपर्क करें',
        findAnswers: 'YugNex Technology, हमारे प्लेटफॉर्म और सॉफ्टवेयर इंजीनियरिंग के भविष्य निर्माण के बारे में सामान्य प्रश्नों के उत्तर प्राप्त करें।',
        headerTagline: 'फाउंडेशनल AI सिस्टम्स लैब · भारत से दुनिया तक',
        brandName: 'युगनेक्स',
    },
    'hi-Latn': {
        vision: 'Vision',
        mission: 'Mission',
        about: 'Hamare Baare Mein',
        research: 'Anusandhan',
        technology: 'Technology',
        platform: 'Platform',
        contact: 'Sampark',
        faq: 'Sawaal-Jawaab',
        connect: 'Judein',
        email: 'Email',
        follow: 'Follow Karein',
        location: 'Sthaan',
        name: 'Naam',
        message: 'Sandesh',
        organization: 'Sangathan',
        submit: 'Submit',
        ourMission: 'Hamara Mission',
        ourVision: 'Hamari Vision',
        useCase: 'Use Case',
        useCases: 'Use Cases',
        theChallenge: 'Challenge',
        ourSolution: 'Hamara Solution',
        philosophy: 'Philosophy',
        whitepaper: 'Whitepaper',
        downloadPDF: 'PDF Download Karein',
        researchPublications: 'Research Publications',
        authors: 'Lekhak',
        published: 'Prakashit',
        openInNewTab: 'Naye Tab Mein Kholein',
        moreResearchComingSoon: 'Jald hi aur research publications aa rahe hain. Updates ke liye humein social media par follow karein.',
        founder: 'Sansthapak',
        ourApproach: 'Hamara Approach',
        support: 'Support',
        frequentlyAskedQuestions: 'Aksar Puche Jaane Wale Sawaal',
        stillHaveQuestions: 'Abhi bhi sawal hain?',
        contactUs: 'Humse Sampark Karein',
        findAnswers: 'YugNex Technology, hamare platform aur software engineering ke bhavishya ke baare mein sawalon ke jawaab paayein.',
        headerTagline: 'Foundational AI Systems Lab · Bharat se Duniya tak',
        brandName: 'YugNex',
    },
    'ta': {
        vision: 'தொலைநோக்கு',
        mission: 'நோக்கம்',
        about: 'எங்களை பற்றி',
        research: 'ஆராய்ச்சி',
        technology: 'தொழில்நுட்பம்',
        platform: 'தளம்',
        contact: 'தொடர்பு',
        faq: 'கேள்வி பதில்',
        connect: 'இணைக்கவும்',
        email: 'மின்னஞ்சல்',
        follow: 'பின்தொடரவும்',
        location: 'இடம்',
        name: 'பெயர்',
        message: 'செய்தி',
        organization: 'நிறுவனம்',
        submit: 'சமர்ப்பிக்கவும்',
        ourMission: 'எங்கள் நோக்கம்',
        ourVision: 'எங்கள் தொலைநோக்கு',
        useCase: 'பயன்பாட்டு வழக்கு',
        useCases: 'பயன்பாட்டு வழக்குகள்',
        theChallenge: 'சவால்',
        ourSolution: 'எங்கள் தீர்வு',
        philosophy: 'தத்துவம்',
        whitepaper: 'ஆய்வறிக்கை',
        downloadPDF: 'PDF பதிவிறக்கம்',
        researchPublications: 'ஆராய்ச்சி வெளியீடுகள்',
        authors: 'ஆசிரியர்கள்',
        published: 'வெளியிடப்பட்டது',
        openInNewTab: 'புதிய தாவலில் திற',
        moreResearchComingSoon: 'மேலும் ஆராய்ச்சி வெளியீடுகள் விரைவில் வருகின்றன. புதுப்பிப்புகளுக்கு சமூக ஊடகத்தில் எங்களைப் பின்தொடரவும்.',
        founder: 'நிறுவனர்',
        ourApproach: 'எங்கள் அணுகுமுறை',
        support: 'ஆதரவு',
        frequentlyAskedQuestions: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
        stillHaveQuestions: 'இன்னும் கேள்விகள் உள்ளதா?',
        contactUs: 'எங்களைத் தொடர்பு கொள்ளுங்கள்',
        findAnswers: 'YugNex Technology, எங்கள் தளம் மற்றும் மென்பொருள் பொறியியலின் எதிர்காலத்தை உருவாக்குவது பற்றிய பொதுவான கேள்விகளுக்கான பதில்களைக் கண்டறியவும்.',
        headerTagline: 'Foundational AI Systems Lab · இந்தியாவிலிருந்து உலகிற்கு',
        brandName: 'யுக்நெக்ஸ்',
    },
    'te': {
        vision: 'విజన్',
        mission: 'మిషన్',
        about: 'మా గురించి',
        research: 'పరిశోధన',
        technology: 'సాంకేతికత',
        platform: 'వేదిక',
        contact: 'సంప్రదించండి',
        faq: 'తరచుగా అడిగే ప్రశ్నలు',
        connect: 'కనెక్ట్',
        email: 'ఇమెయిల్',
        follow: 'ఫాలో',
        location: 'స్థానం',
        name: 'పేరు',
        message: 'సందేశం',
        organization: 'సంస్థ',
        submit: 'సమర్పించు',
        ourMission: 'మా మిషన్',
        ourVision: 'మా దృష్టి',
        useCase: 'వినియోగ సందర్భం',
        useCases: 'వినియోగ సందర్భాలు',
        theChallenge: 'సవాలు',
        ourSolution: 'మా పరిష్కారం',
        philosophy: 'తత్వశాస్త్రం',
        whitepaper: 'శ్వేతపత్రం',
        downloadPDF: 'PDF డౌన్‌లోడ్',
        researchPublications: 'పరిశోధన ప్రచురణలు',
        authors: 'రచయితలు',
        published: 'ప్రచురించబడింది',
        openInNewTab: 'కొత్త ట్యాబ్‌లో తెరువండి',
        moreResearchComingSoon: 'త్వరలో మరిన్ని పరిశోధన ప్రచురణలు వస్తున్నాయి. నవీకరణల కోసం మమ్మల్ని సోషల్ మీడియాలో అనుసరించండి.',
        founder: 'వ్యవస్థాపకుడు',
        ourApproach: 'మా విధానం',
        support: 'మద్దతు',
        frequentlyAskedQuestions: 'తరచుగా అడిగే ప్రశ్నలు',
        stillHaveQuestions: 'ఇంకా ప్రశ్నలు ఉన్నాయా?',
        contactUs: 'మమ్మల్ని సంప్రదించండి',
        findAnswers: 'YugNex Technology, మా ప్లాట్‌ఫారమ్ మరియు సాఫ్ట్‌వేర్ ఇంజినీరింగ్ భవిష్యత్తును నిర్మించడం గురించి సాధారణ ప్రశ్నలకు సమాధానాలను కనుగొనండి.',
        headerTagline: 'Foundational AI Systems Lab · భారతదేశం నుంచి లోకం వరకు',
        brandName: 'యుగ్నెక్స్',
    },
    'bn': {
        vision: 'দৃষ্টিভঙ্গি',
        mission: 'মিশন',
        about: 'আমাদের সম্পর্কে',
        research: 'গবেষণা',
        technology: 'প্রযুক্তি',
        platform: 'প্ল্যাটফর্ম',
        contact: 'যোগাযোগ',
        faq: 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
        connect: 'সংযুক্ত হন',
        email: 'ইমেইল',
        follow: 'অনুসরণ করুন',
        location: 'অবস্থান',
        name: 'নাম',
        message: 'বার্তা',
        organization: 'সংস্থা',
        submit: 'জমা দিন',
        ourMission: 'আমাদের মিশন',
        ourVision: 'আমাদের দৃষ্টিভঙ্গি',
        useCase: 'ব্যবহারের ক্ষেত্রে',
        useCases: 'ব্যবহারের ক্ষেত্রে',
        theChallenge: 'চ্যালেঞ্জ',
        ourSolution: 'আমাদের সমাধান',
        philosophy: 'দর্শন',
        whitepaper: 'শ্বেতপত্র',
        downloadPDF: 'PDF ডাউনলোড',
        researchPublications: 'গবেষণা প্রকাশনা',
        authors: 'লেখক',
        published: 'প্রকাশিত',
        openInNewTab: 'নতুন ট্যাবে খুলুন',
        moreResearchComingSoon: 'শীঘ্রই আরও গবষণা প্রকাশনা আসছে। আপডেটের জন্য সোশ্যাল মিডিয়ায় আমাদের অনুসরণ করুন।',
        founder: 'প্রতিষ্ঠাতা',
        ourApproach: 'আমাদের পদ্ধতি',
        support: 'সহায়তা',
        frequentlyAskedQuestions: 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
        stillHaveQuestions: 'এখনও প্রশ্ন আছে?',
        contactUs: 'আমাদের সাথে যোগাযোগ করুন',
        findAnswers: 'YugNex Technology, আমাদের প্ল্যাটফর্ম এবং সফটওয়্যার ইঞ্জিনিয়ারিংয়ের ভবিষ্যত নির্মাণ সম্পর্কে সাধারণ প্রশ্নের উত্তর খুঁজুন।',
        headerTagline: 'Foundational AI Systems Lab · ভারত থেকে বিশ্বে',
        brandName: 'ইউগনেক্স',
    },
    'mr': {
        vision: 'व्हिजन',
        mission: 'मिशन',
        about: 'आमच्याबद्दल',
        research: 'संशोधन',
        technology: 'तंत्रज्ञान',
        platform: 'प्लॅटफॉर्म',
        contact: 'संपर्क',
        faq: 'सामान्य प्रश्न',
        connect: 'कनेक्ट',
        email: 'ईमेल',
        follow: 'फॉलो',
        location: 'स्थान',
        name: 'नाव',
        message: 'संदेश',
        organization: 'संस्था',
        submit: 'सबमिट',
        ourMission: 'आमचे मिशन',
        ourVision: 'आमचे व्हिजन',
        useCase: 'वापर प्रकरण',
        useCases: 'वापर प्रकरणे',
        theChallenge: 'आव्हान',
        ourSolution: 'आमचे समाधान',
        philosophy: 'तत्वज्ञान',
        whitepaper: 'श्वेतपत्र',
        downloadPDF: 'PDF डाउनलोड',
        researchPublications: 'संशोधन प्रकाशने',
        authors: 'लेखक',
        published: 'प्रकाशित',
        openInNewTab: 'नवीन टॅबमध्ये उघडा',
        moreResearchComingSoon: 'लवकरच अधिक संशोधन प्रकाशने येत आहेत. अपडेट्ससाठी आम्हाला सोशल मीडियावर फॉलो करा.',
        founder: 'संस्थापक',
        ourApproach: 'आमचा दृष्टिकोन',
        support: 'समर्थन',
        frequentlyAskedQuestions: 'वारंवार विचारले जाणारे प्रश्न',
        stillHaveQuestions: 'अजूनही प्रश्न आहेत?',
        contactUs: 'आमच्याशी संपर्क साधा',
        findAnswers: 'YugNex Technology, आमचे प्लॅटफॉर्म आणि सॉफ्टवेअर अभियांत्रिकीचे भविष्य तयार करण्याबाबत सामान्य प्रश्नांची उत्तरे शोधा.',
        headerTagline: 'Foundational AI Systems Lab · भारतापासून जगात',
        brandName: 'युगनेक्स',
    },
    'gu': {
        vision: 'વિઝન',
        mission: 'મિશન',
        about: 'અમારા વિશે',
        research: 'સંશોધન',
        technology: 'ટેકનોલોજી',
        platform: 'પ્લેટફોર્મ',
        contact: 'સંપર્ક',
        faq: 'સામાન્ય પ્રશ્નો',
        connect: 'કનેક્ટ',
        email: 'ઈમેલ',
        follow: 'ફોલો',
        location: 'સ્થાન',
        name: 'નામ',
        message: 'સંદેશ',
        organization: 'સંસ્થા',
        submit: 'સબમિટ',
        ourMission: 'અમારું મિશન',
        ourVision: 'અમારું વિઝન',
        useCase: 'ઉપયોગ કેસ',
        useCases: 'ઉપયોગ કેસ',
        theChallenge: 'પડકાર',
        ourSolution: 'અમારું સોલ્યુશન',
        philosophy: 'ફિલોસોફી',
        whitepaper: 'વ્હાઇટપેપર',
        downloadPDF: 'PDF ડાઉનલોડ',
        researchPublications: 'સંશોધન પ્રકાશનો',
        authors: 'લેખકો',
        published: 'પ્રકાશિત',
        openInNewTab: 'નવા ટૅબમાં ખોલો',
        moreResearchComingSoon: 'ટૂંક સમયમાં વધુ સંશોધન પ્રકાશનો આવી રહ્યા છે. અપડેટ્સ માટે અમને સોશિયલ મીડિયા પર ફોલો કરો.',
        founder: 'સ્થાપક',
        ourApproach: 'અમારો અભિગમ',
        support: 'સહાય',
        frequentlyAskedQuestions: 'વારંવાર પૂછાતા પ્રશ્નો',
        stillHaveQuestions: 'હજુ પણ પ્રશ્નો છે?',
        contactUs: 'અમારો સંપર્ક કરો',
        findAnswers: 'YugNex Technology, અમારું પ્લેટફોર્મ અને સોફ્ટવેર એન્જિનિયરિંગનું ભવિષ્ય બનાવવા વિશે સામાન્ય પ્રશ્નોના જવાબો શોધો.',
        headerTagline: 'Foundational AI Systems Lab · ભારતથી વિશ્વ સુધી',
        brandName: 'યુગનેક્સ',
    },
    'kn': {
        vision: 'ದೃಷ್ಟಿ',
        mission: 'ಮಿಷನ್',
        about: 'ನಮ್ಮ ಬಗ್ಗೆ',
        research: 'ಸಂಶೋಧನೆ',
        technology: 'ತಂತ್ರಜ್ಞಾನ',
        platform: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
        contact: 'ಸಂಪರ್ಕಿಸಿ',
        faq: 'ಪುನಃಪುನಃ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
        connect: 'ಸಂಪರ್ಕ',
        email: 'ಇಮೇಲ್',
        follow: 'ಅನುಸರಿಸಿ',
        location: 'ಸ್ಥಳ',
        name: 'ಹೆಸರು',
        message: 'ಸಂದೇಶ',
        organization: 'ಸಂಸ್ಥೆ',
        submit: 'ಸಲ್ಲಿಸಿ',
        ourMission: 'ನಮ್ಮ ಮಿಷನ್',
        ourVision: 'ನಮ್ಮ ದೃಷ್ಟಿ',
        useCase: 'ಬಳಕೆ ಪ್ರಕರಣ',
        useCases: 'ಬಳಕೆ ಪ್ರಕರಣಗಳು',
        theChallenge: 'ಸವಾಲು',
        ourSolution: 'ನಮ್ಮ ಪರಿಹಾರ',
        philosophy: 'ತತ್ವಶಾಸ್ತ್ರ',
        whitepaper: 'ಶ್ವೇತಪತ್ರ',
        downloadPDF: 'PDF ಡೌನ್‌ಲೋಡ್',
        researchPublications: 'ಸಂಶೋಧನಾ ಪ್ರಕಟಣೆಗಳು',
        authors: 'ಲೇಖಕರು',
        published: 'ಪ್ರಕಟಿಸಲಾಗಿದೆ',
        openInNewTab: 'ಹೊಸ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
        moreResearchComingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಹೆಚ್ಚಿನ ಸಂಶೋಧನಾ ಪ್ರಕಟಣೆಗಳು ಬರುತ್ತಿವೆ. ನವೀಕರಣಗಳಿಗಾಗಿ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ.',
        founder: 'ಸಂಸ್ಥಾಪಕ',
        ourApproach: 'ನಮ್ಮ ವಿಧಾನ',
        support: 'ಬೆಂಬಲ',
        frequentlyAskedQuestions: 'ಆಗಾಗ್ಗೆ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
        stillHaveQuestions: 'ಇನ್ನೂ ಪ್ರಶ್ನೆಗಳಿವೆಯೇ?',
        contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
        findAnswers: 'YugNex Technology, ನಮ್ಮ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಮತ್ತು ಸಾಫ್ಟ್‌ವೇರ್ ಇಂಜಿನಿಯರಿಂಗ್‌ನ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸುವ ಬಗ್ಗೆ ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳನ್ನು ಹುಡುಕಿ.',
        headerTagline: 'Foundational AI Systems Lab · ಭಾರತದಿಂದ ಲೋಕಕ್ಕೆ',
        brandName: 'ಯುಗ್ನೆಕ್ಸ್',
    },
    'ml': {
        vision: 'ദർശനം',
        mission: 'ദൗത്യം',
        about: 'ഞങ്ങളെക്കുറിച്ച്',
        research: 'ഗവേഷണം',
        technology: 'സാങ്കേതികവിദ്യ',
        platform: 'പ്ലാറ്റ്ഫോം',
        contact: 'ബന്ധപ്പെടുക',
        faq: 'പതിവ് ചോദ്യങ്ങൾ',
        connect: 'കണക്ട്',
        email: 'ഇമെയിൽ',
        follow: 'പിന്തുടരുക',
        location: 'സ്ഥലം',
        name: 'പേര്',
        message: 'സന്ദേശം',
        organization: 'സംഘടന',
        submit: 'സമർപ്പിക്കുക',
        ourMission: 'ഞങ്ങളുടെ ദൗത്യം',
        ourVision: 'ഞങ്ങളുടെ ദർശനം',
        useCase: 'ഉപയോഗ കേസ്',
        useCases: 'ഉപയോഗ കേസുകൾ',
        theChallenge: 'വെല്ലുവിളി',
        ourSolution: 'ഞങ്ങളുടെ പരിഹാരം',
        philosophy: 'തത്വശാസ്ത്രം',
        whitepaper: 'വൈറ്റ്പേപ്പർ',
        downloadPDF: 'PDF ഡൗൺലോഡ്',
        researchPublications: 'ഗവേഷണ പ്രസിദ്ധീകരണങ്ങൾ',
        authors: 'രചയിതാക്കൾ',
        published: 'പ്രസിദ്ധീകരിച്ചത്',
        openInNewTab: 'പുതിയ ടാബിൽ തുറക്കുക',
        moreResearchComingSoon: 'കൂടുതൽ ഗവേഷണ പ്രസിദ്ധീകരണങ്ങൾ ഉടൻ വരുന്നു. അപ്ഡേറ്റുകൾക്കായി സോഷ്യൽ മീഡിയയിൽ ഞങ്ങളെ പിന്തുടരുക.',
        founder: 'സ്ഥാപകൻ',
        ourApproach: 'ഞങ്ങളുടെ സമീപനം',
        support: 'പിന്തുണ',
        frequentlyAskedQuestions: 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ',
        stillHaveQuestions: 'ഇനിയും ചോദ്യങ്ങൾ ഉണ്ടോ?',
        contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
        findAnswers: 'YugNex Technology, ഞങ്ങളുടെ പ്ലാറ്റ്ഫോം, സോഫ്റ്റ്‌വെയർ എഞ്ചിനീയറിംഗിന്റെ ഭാവി നിർമ്മിക്കുന്നത് എന്നിവയെക്കുറിച്ചുള്ള പൊതു ചോദ്യങ്ങൾക്ക് ഉത്തരം കണ്ടെത്തുക.',
        headerTagline: 'Foundational AI Systems Lab · ഇന്ത്യയിൽ നിന്ന് ലോകത്തിലേക്ക്',
        brandName: 'യുഗ്നെക്സ്',
    },
    'pa': {
        vision: 'ਵਿਜ਼ਨ',
        mission: 'ਮਿਸ਼ਨ',
        about: 'ਸਾਡੇ ਬਾਰੇ',
        research: 'ਖੋਜ',
        technology: 'ਤਕਨਾਲੋਜੀ',
        platform: 'ਪਲੇਟਫਾਰਮ',
        contact: 'ਸੰਪਰਕ',
        faq: 'ਆਮ ਸਵਾਲ',
        connect: 'ਕਨੈਕਟ',
        email: 'ਈਮੇਲ',
        follow: 'ਫਾਲੋ',
        location: 'ਸਥਾਨ',
        name: 'ਨਾਮ',
        message: 'ਸੁਨੇਹਾ',
        organization: 'ਸੰਗਠਨ',
        submit: 'ਜਮ੍ਹਾਂ',
        ourMission: 'ਸਾਡਾ ਮਿਸ਼ਨ',
        ourVision: 'ਸਾਡੀ ਵਿਜ਼ਨ',
        useCase: 'ਵਰਤੋਂ ਕੇਸ',
        useCases: 'ਵਰਤੋਂ ਕੇਸ',
        theChallenge: 'ਚੁਣੌਤੀ',
        ourSolution: 'ਸਾਡਾ ਹੱਲ',
        philosophy: 'ਫਿਲਾਸਫੀ',
        whitepaper: 'ਵਾਈਟਪੇਪਰ',
        downloadPDF: 'PDF ਡਾਊਨਲੋਡ',
        researchPublications: 'ਖੋਜ ਪ੍ਰਕਾਸ਼ਨ',
        authors: 'ਲੇਖਕ',
        published: 'ਪ੍ਰਕਾਸ਼ਿਤ',
        openInNewTab: 'ਨਵੀਂ ਟੈਬ ਵਿੱਚ ਖੋਲ੍ਹੋ',
        moreResearchComingSoon: 'ਜਲਦੀ ਹੀ ਹੋਰ ਖੋਜ ਪ੍ਰਕਾਸ਼ਨ ਆ ਰਹੇ ਹਨ। ਅੱਪਡੇਟਸ ਲਈ ਸਾਨੂੰ ਸੋਸ਼ਲ ਮੀਡੀਆ ਤੇ ਫਾਲੋ ਕਰੋ.',
        founder: 'ਸੰਸਥਾਪਕ',
        ourApproach: 'ਸਾਡੀ ਪਹੁੰਚ',
        support: 'ਸਹਾਇਤਾ',
        frequentlyAskedQuestions: 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
        stillHaveQuestions: 'ਅਜੇ ਵੀ ਸਵਾਲ ਹਨ?',
        contactUs: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
        findAnswers: 'YugNex Technology, ਸਾਡੇ ਪਲੇਟਫਾਰਮ ਅਤੇ ਸਾਫਟਵੇਅਰ ਇੰਜੀਨੀਅਰਿੰਗ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣ ਬਾਰੇ ਆਮ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਲੱਭੋ.',
        headerTagline: 'Foundational AI Systems Lab · ਭਾਰਤ ਤੋਂ ਦੁਨੀਆ ਤੱਕ',
        brandName: 'ਯੁਗਨੇਕਸ',
    },
    'fr': {
        vision: 'Vision',
        mission: 'Mission',
        about: 'À propos',
        research: 'Recherche',
        technology: 'Technologie',
        platform: 'Plateforme',
        contact: 'Contact',
        faq: 'FAQ',
        connect: 'Connecter',
        email: 'E-mail',
        follow: 'Suivre',
        location: 'Emplacement',
        name: 'Nom',
        message: 'Message',
        organization: 'Organisation',
        submit: 'Soumettre',
        ourMission: 'Notre Mission',
        ourVision: 'Notre Vision',
        useCase: 'Cas d\'usage',
        useCases: 'Cas d\'usage',
        theChallenge: 'Le Défi',
        ourSolution: 'Notre Solution',
        philosophy: 'Philosophie',
        whitepaper: 'Livre blanc',
        downloadPDF: 'Télécharger PDF',
        researchPublications: 'Publications de recherche',
        authors: 'Auteurs',
        published: 'Publié',
        openInNewTab: 'Ouvrir dans un nouvel onglet',
        moreResearchComingSoon: 'Plus de publications de recherche arrivent bientôt. Suivez-nous sur les réseaux sociaux pour les mises à jour.',
        founder: 'Fondateur',
        ourApproach: 'Notre approche',
        support: 'Support',
        frequentlyAskedQuestions: 'Questions fréquement posées',
        stillHaveQuestions: 'Encore des questions ?',
        contactUs: 'Contactez-nous',
        findAnswers: 'Trouvez des réponses aux questions courantes sur YugNex Technology, notre plateforme et comment nous construisons l\'avenir du génie logiciel.',
        headerTagline: 'Laboratoire de systèmes d\'IA fondamentaux · De l\'Inde au monde',
        brandName: 'YugNex',
    },
    'de': {
        vision: 'Vision',
        mission: 'Mission',
        about: 'Über uns',
        research: 'Forschung',
        technology: 'Technologie',
        platform: 'Plattform',
        contact: 'Kontakt',
        faq: 'FAQ',
        connect: 'Verbinden',
        email: 'E-Mail',
        follow: 'Folgen',
        location: 'Standort',
        name: 'Name',
        message: 'Nachricht',
        organization: 'Organisation',
        submit: 'Senden',
        ourMission: 'Unsere Mission',
        ourVision: 'Unsere Vision',
        useCase: 'Anwendungsfall',
        useCases: 'Anwendungsfälle',
        theChallenge: 'Die Herausforderung',
        ourSolution: 'Unsere Lösung',
        philosophy: 'Philosophie',
        whitepaper: 'Whitepaper',
        downloadPDF: 'PDF herunterladen',
        researchPublications: 'Forschungspublikationen',
        authors: 'Autoren',
        published: 'Veröffentlicht',
        openInNewTab: 'In neuem Tab öffnen',
        moreResearchComingSoon: 'Weitere Forschungspublikationen folgen in Kürze. Folgen Sie uns in den sozialen Medien für Updates.',
        founder: 'Gründer',
        ourApproach: 'Unser Ansatz',
        support: 'Support',
        frequentlyAskedQuestions: 'Häufig gestellte Fragen',
        stillHaveQuestions: 'Haben Sie noch Fragen?',
        contactUs: 'Kontaktieren Sie uns',
        findAnswers: 'Finden Sie Antworten auf häufige Fragen zu YugNex Technology, unserer Plattform und wie wir die Zukunft der Softwareentwicklung gestalten.',
        headerTagline: 'Grundlegendes KI-Systemlabor · Von Indien in die Welt',
        brandName: 'YugNex',
    },
    'ja': {
        vision: 'ビジョン',
        mission: 'ミッション',
        about: '会社概要',
        research: '研究',
        technology: 'テクノロジー',
        platform: 'プラットフォーム',
        contact: 'お問い合わせ',
        faq: 'よくある質問',
        connect: '接続',
        email: 'メール',
        follow: 'フォローfollow',
        location: '場所',
        name: '名前',
        message: 'メッセージ',
        organization: '組織',
        submit: '送信',
        ourMission: '私たちのミッション',
        ourVision: '私たちのビジョン',
        useCase: 'ユースケース',
        useCases: 'ユースケース',
        theChallenge: '課題',
        ourSolution: '私たちのソリューション',
        philosophy: '哲学',
        whitepaper: 'ホワイトペーパー',
        downloadPDF: 'PDFダウンロード',
        researchPublications: '研究出版物',
        authors: '著者',
        published: '公開済み',
        openInNewTab: '新しいタブで開く',
        moreResearchComingSoon: 'さらなる研究出版物がまもなく公開されます。最新情報についてはソーシャルメディアでフォローしてください。',
        founder: '創設者',
        ourApproach: '私たちのアプローチ',
        support: 'サポート',
        frequentlyAskedQuestions: 'よくある質問',
        stillHaveQuestions: 'ご質問がありますか？',
        contactUs: 'お問い合わせ',
        findAnswers: 'YugNex Technology、プラットフォーム、そしてソフトウェアエンジニアリングの未来をどのように構築しているかについての一般的な質問への回答を見つけてください。',
        headerTagline: '基礎AIシステムラボ · インドから世界へ',
        brandName: 'YugNex',
    },
    'es': {
        vision: 'Visión',
        mission: 'Misión',
        about: 'Acerca de',
        research: 'Investigación',
        technology: 'Tecnología',
        platform: 'Plataforma',
        contact: 'Contacto',
        faq: 'Preguntas frecuentes',
        connect: 'Conectar',
        email: 'Correo electrónico',
        follow: 'Seguir',
        location: 'Ubicación',
        name: 'Nombre',
        message: 'Mensaje',
        organization: 'Organización',
        submit: 'Enviar',
        ourMission: 'Nuestra Misión',
        ourVision: 'Nuestra Visión',
        useCase: 'Caso de uso',
        useCases: 'Casos de uso',
        theChallenge: 'El Desafío',
        ourSolution: 'Nuestra Solución',
        philosophy: 'Filosofía',
        whitepaper: 'Documento técnico',
        downloadPDF: 'Descargar PDF',
        researchPublications: 'Publicaciones de investigación',
        authors: 'Autores',
        published: 'Publicado',
        openInNewTab: 'Abrir en nueva pestaña',
        moreResearchComingSoon: 'Próximamente más publicaciones de investigación. Síguenos en redes sociales para actualizaciones.',
        founder: 'Fundador',
        ourApproach: 'Nuestro enfoque',
        support: 'Soporte',
        frequentlyAskedQuestions: 'Preguntas frecuentes',
        stillHaveQuestions: '¿Todavía tienes preguntas?',
        contactUs: 'Contáctanos',
        findAnswers: 'Encuentra respuestas a preguntas frecuentes sobre YugNex Technology, nuestra plataforma y cómo estamos construyendo el futuro de la ingeniería de software.',
        headerTagline: 'Laboratorio de sistemas de IA fundamentales · De la India para el mundo',
        brandName: 'YugNex',
    },
    'pt': {
        vision: 'Visão',
        mission: 'Missão',
        about: 'Sobre',
        research: 'Pesquisa',
        technology: 'Tecnologia',
        platform: 'Plataforma',
        contact: 'Contato',
        faq: 'Perguntas frequentes',
        connect: 'Conectar',
        email: 'E-mail',
        follow: 'Seguir',
        location: 'Localização',
        name: 'Nome',
        message: 'Mensagem',
        organization: 'Organização',
        submit: 'Enviar',
        ourMission: 'Nossa Missão',
        ourVision: 'Nossa Visão',
        useCase: 'Caso de uso',
        useCases: 'Casos de uso',
        theChallenge: 'O Desafio',
        ourSolution: 'Nossa Solução',
        philosophy: 'Filosofia',
        whitepaper: 'Whitepaper',
        downloadPDF: 'Baixar PDF',
        researchPublications: 'Publicações de pesquisa',
        authors: 'Autores',
        published: 'Publicado',
        openInNewTab: 'Abrir em nova aba',
        moreResearchComingSoon: 'Mais publicações de pesquisa em breve. Siga-nos nas redes sociais para atualizações.',
        founder: 'Fundador',
        ourApproach: 'Nossa abordagem',
        support: 'Suporte',
        frequentlyAskedQuestions: 'Perguntas frequentes',
        stillHaveQuestions: 'Ainda tem perguntas?',
        contactUs: 'Contate-nos',
        findAnswers: 'Encontre respostas para perguntas comuns sobre a YugNex Technology, nossa plataforma e como estamos construindo o futuro da engenharia de software.',
        headerTagline: 'Laboratório de Sistemas de IA Fundamentais · Da Índia para o Mundo',
        brandName: 'YugNex',
    },
    'zh': {
        vision: '愿景',
        mission: '使命',
        about: '关于我们',
        research: '研究',
        technology: '技术',
        platform: '平台',
        contact: '联系',
        faq: '常见问题',
        connect: '连接',
        email: '电子邮件',
        follow: '关注',
        location: '位置',
        name: '姓名',
        message: '消息',
        organization: '组织',
        submit: '提交',
        ourMission: '我们的使命',
        ourVision: '我们的愿景',
        useCase: '用例',
        useCases: '用例',
        theChallenge: '挑战',
        ourSolution: '我们的解决方案',
        philosophy: '理念',
        whitepaper: '白皮书',
        downloadPDF: '下载PDF',
        researchPublications: '研究出版物',
        authors: '作者',
        published: '已发布',
        openInNewTab: '在新标签页打开',
        moreResearchComingSoon: '更多研究出版物即将发布。请在社交媒体上关注我们以获取更新。',
        founder: '创始人',
        ourApproach: '我们的方法',
        support: '支持',
        frequentlyAskedQuestions: '常见问题',
        stillHaveQuestions: '还有问题吗？',
        contactUs: '联系我们',
        findAnswers: '查找有关 YugNex Technology、我们的平台以及我们如何构建软件工程未来的常见问题的答案。',
        headerTagline: '基础人工智能系统实验室 · 从印度走向世界',
        brandName: 'YugNex',
    },
    'ar': {
        vision: 'الرؤية',
        mission: 'المهمة',
        about: 'من نحن',
        research: 'البحث',
        technology: 'التكنولوجيا',
        platform: 'المنصة',
        contact: 'اتصل بنا',
        faq: 'الأسئلة الشائعة',
        connect: 'اتصل',
        email: 'البريد الإلكتروني',
        follow: 'تابع',
        location: 'الموقع',
        name: 'الاسم',
        message: 'الرسالة',
        organization: 'المنظمة',
        submit: 'إرسال',
        ourMission: 'مهمتنا',
        ourVision: 'رؤيتنا',
        useCase: 'حالة الاستخدام',
        useCases: 'حالات الاستخدام',
        theChallenge: 'التحدي',
        ourSolution: 'حلنا',
        philosophy: 'الفلسفة',
        whitepaper: 'الورقة البيضاء',
        downloadPDF: 'تحميل PDF',
        researchPublications: 'منشورات البحث',
        authors: 'المؤلفون',
        published: 'نشرت',
        openInNewTab: 'فتح في علامة تبويب جديدة',
        moreResearchComingSoon: 'المزيد من المنشورات البحثية قادمة قريبا. تابعنا على وسائل التواصل الاجتماعي للحصول على التحديثات.',
        founder: 'المؤسس',
        ourApproach: 'نهجنا',
        support: 'الدعم',
        frequentlyAskedQuestions: 'الأسئلة الشائعة',
        stillHaveQuestions: 'لا تزال لديك أسئلة؟',
        contactUs: 'اتصل بنا',
        findAnswers: 'اعثر على إجابات للأسئلة الشائعة حول YugNex Technology ومنصتنا وكيف نبني مستقبل هندسة البرمجيات.',
        headerTagline: 'مختبر أنظمة الذكاء الاصطناعي التأسيسي · من الهند إلى العالم',
        brandName: 'YugNex',
    },
    'ru': {
        vision: 'Видение',
        mission: 'Миссия',
        about: 'О нас',
        research: 'Исследования',
        technology: 'Технология',
        platform: 'Платформа',
        contact: 'Контакт',
        faq: 'Часто задаваемые вопросы',
        connect: 'Связаться',
        email: 'Электронная почта',
        follow: 'Следовать',
        location: 'Местоположение',
        name: 'Имя',
        message: 'Сообщение',
        organization: 'Организация',
        submit: 'Отправить',
        ourMission: 'Наша Миссия',
        ourVision: 'Наше Видение',
        useCase: 'Вариант использования',
        useCases: 'Варианты использования',
        theChallenge: 'Вызов',
        ourSolution: 'Наше Решение',
        philosophy: 'Философия',
        whitepaper: 'Технический документ',
        downloadPDF: 'Скачать PDF',
        researchPublications: 'Научные публикации',
        authors: 'Авторы',
        published: 'Опубликовано',
        openInNewTab: 'Открыть в новой вкладке',
        moreResearchComingSoon: 'Скоро появятся новые научные публикации. Следите за обновлениями в социальных сетях.',
        founder: 'Основатель',
        ourApproach: 'Наш подход',
        support: 'Поддержка',
        frequentlyAskedQuestions: 'Часто задаваемые вопросы',
        stillHaveQuestions: 'У вас все еще есть вопросы?',
        contactUs: 'Свяжитесь с нами',
        findAnswers: 'Найдите ответы на часто задаваемые вопросы о YugNex Technology, нашей платформе и о том, как мы строим будущее программной инженерии.',
        headerTagline: 'Лаборатория фундаментальных систем ИИ · Из Индии в мир',
        brandName: 'YugNex',
    },
    'ko': {
        vision: '비전',
        mission: '미션',
        about: '회사 소개',
        research: '연구',
        technology: '기술',
        platform: '플랫폼',
        contact: '연락처',
        faq: '자주 묻는 질문',
        connect: '연결',
        email: '이메일',
        follow: '팔로우',
        location: '위치',
        name: '이름',
        message: '메시지',
        organization: '조직',
        submit: '제출',
        ourMission: '우리의 미션',
        ourVision: '우리의 비전',
        useCase: '사용 사례',
        useCases: '사용 사례',
        theChallenge: '도전',
        ourSolution: '우리의 솔루션',
        philosophy: '철학',
        whitepaper: '백서',
        downloadPDF: 'PDF 다운로드',
        researchPublications: '연구 간행물',
        authors: '저자',
        published: '게시됨',
        openInNewTab: '새 탭에서 열기',
        moreResearchComingSoon: '더 많은 연구 간행물이 곧 제공될 예정입니다. 업데이트를 위해 소셜 미디어에서 팔로우하세요.',
        founder: '설립자',
        ourApproach: '우리의 접근 방식',
        support: '지원',
        frequentlyAskedQuestions: '자주 묻는 질문',
        stillHaveQuestions: '여전히 질문이 있으신가요?',
        contactUs: '문의하기',
        findAnswers: 'YugNex Technology, 플랫폼 및 소프트웨어 엔지니어링의 미래를 구축하는 방법에 대한 일반적인 질문에 대한 답변을 찾으십시오.',
        headerTagline: '기초 AI 시스템 연구소 · 인도에서 세계로',
        brandName: 'YugNex',
    },
}

/**
 * Get UI labels for a specific locale
 */
export function getUILabels(locale: Locale) {
    return UI_LABELS[locale] || UI_LABELS['en']
}
